### ISSUE TITLE
新增標記

### ISSUE THREAD

**Issue by kc944201** [DylanLN/virtual_wall#1]
@DylanLN 你好，請問這個虛擬牆插件要可以新增ROS裡的標記嗎?
類似像下面的圖，想要在虛擬牆上增加標記可以更顯目。 謝謝!
![image](https://user-images.githubusercontent.com/57080316/125552304-bf5d907c-2d96-4fc9-af94-df37e2d07882.png)

**Comment by DylanLN** [comment]
这是一个不错的想法但需要时间去实现,如果你有此想法欢迎fork。

**Comment by DylanLN** [comment]
我尝试coding，现在做了类似栅栏的效果，真是一个不错的想法。等我回到家会将代码重新编辑就会发布[https://img-blog.csdnimg.cn/20210714115646203.jpg](img_url)

**Comment by kc944201** [comment]
Cool! 期待你的更新

**Comment by kc944201** [comment]
@DylanLN 你好，請問最近兩天有時間更新嗎? 謝謝

**Comment by kc944201** [comment]
@kc944201 你好，我有嘗試加入標記但似乎沒作用...
想請問你哪時候有空更新呢?

**Comment by kc944201** [comment]
@DylanLN  你好，我有嘗試加入標記但似乎沒作用...
想請問你哪時候有空更新呢?

**Comment by DylanLN** [comment]
我先更新一版可以进行显示，但是这个代码没有进行优化，最近在忙于其他事情有时间再对其进行优化

**Comment by DylanLN** [comment]
Hi! kc944201.我更新了显示，如果你有时间的话可以测试一下

**Comment by kc944201** [comment]
@DylanLN 謝謝! 測試後確認可以使用~
